<template><div><h1 id="plan-combination-model" tabindex="-1"><a class="header-anchor" href="#plan-combination-model"><span>Plan Combination Model</span></a></h1>
<nav class="table-of-contents"><ul><li><router-link to="#create-a-plan-combination">Create a Plan Combination</router-link></li><li><router-link to="#get-plan-combination-details">Get Plan Combination details</router-link></li><li><router-link to="#subscribe-to-plan-combination">Subscribe to plan combination</router-link></li><li><router-link to="#change-subscription-s-plan-to-plan-combination">Change subscription&#39;s plan to plan combination</router-link></li><li><router-link to="#schedule-subscription-s-plan-change-to-plan-combination">Schedule subscription&#39;s plan change to plan combination</router-link></li></ul></nav>
<p>With this model you define your plan combinations. You can have multiple prices and intervals per currency, country,
etc.</p>
<h2 id="create-a-plan-combination" tabindex="-1"><a class="header-anchor" href="#create-a-plan-combination"><span>Create a Plan Combination</span></a></h2>
<p>Combinations must be unique for <code v-pre>country</code>, <code v-pre>currency</code>, <code v-pre>invoice_period</code> and <code v-pre>invoice_interval</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>Plan</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>PlanCombination</span><span class="token punctuation">;</span>

<span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">getByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'basic'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$plan</span><span class="token operator">-></span><span class="token function">combinations</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
    <span class="token string single-quoted-string">'tag'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'basic-es-eur-1-year'</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'country'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'ESP'</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'currency'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'EUR'</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'price'</span> <span class="token operator">=></span> <span class="token number">99.99</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'invoice_period'</span> <span class="token operator">=></span> <span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'invoice_interval'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'year'</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="get-plan-combination-details" tabindex="-1"><a class="header-anchor" href="#get-plan-combination-details"><span>Get Plan Combination details</span></a></h2>
<p>You can query the plan combination for further details as follows:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$planCombination</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanCombination</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Or querying by tag</span>
<span class="token variable">$planCombination</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanCombination</span><span class="token operator">::</span><span class="token function">getByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'basic-es-eur-1-year'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Or do your own query</span>
<span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">getByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'basic'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$planCombination</span> <span class="token operator">=</span> <span class="token variable">$plan</span><span class="token operator">-></span><span class="token function">combinations</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'country'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ESP'</span><span class="token punctuation">)</span>
                                        <span class="token operator">-></span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'currency'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'EUR'</span><span class="token punctuation">)</span>
                                        <span class="token operator">-></span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'invoice_period'</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span>
                                        <span class="token operator">-></span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'invoice_interval'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'year'</span><span class="token punctuation">)</span>
                                        <span class="token operator">-></span><span class="token function">first</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get parent plan                </span>
<span class="token variable">$planCombination</span><span class="token operator">-></span><span class="token property">plan</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="subscribe-to-plan-combination" tabindex="-1"><a class="header-anchor" href="#subscribe-to-plan-combination"><span>Subscribe to plan combination</span></a></h2>
<p>See <RouteLink to="/v7.x/models/plan-subscription-model.html#create-a-subscription">create a Subscription</RouteLink> and use a <code v-pre>PlanCombination</code> instead of a
<code v-pre>Plan</code>.</p>
<h2 id="change-subscription-s-plan-to-plan-combination" tabindex="-1"><a class="header-anchor" href="#change-subscription-s-plan-to-plan-combination"><span>Change subscription's plan to plan combination</span></a></h2>
<p>See <RouteLink to="/v7.x/models/plan-subscription-model.html#change-its-plan">change its plan</RouteLink> and use a <code v-pre>PlanCombination</code> instead of a <code v-pre>Plan</code>.</p>
<h2 id="schedule-subscription-s-plan-change-to-plan-combination" tabindex="-1"><a class="header-anchor" href="#schedule-subscription-s-plan-change-to-plan-combination"><span>Schedule subscription's plan change to plan combination</span></a></h2>
<p>See <RouteLink to="/v7.x/models/plan-subscription-schedule-model.html#create-schedule">create schedule</RouteLink> and use a <code v-pre>PlanCombination</code> instead of a
<code v-pre>Plan</code>.</p>
</div></template>


