<template><div><h1 id="plan-subscription-model" tabindex="-1"><a class="header-anchor" href="#plan-subscription-model"><span>Plan Subscription Model</span></a></h1>
<h2 id="create-a-subscription" tabindex="-1"><a class="header-anchor" href="#create-a-subscription"><span>Create a Subscription<a name="create-subscription"></a></span></a></h2>
<p>You can subscribe a user (or any model correctly traited) to a plan by using the <code v-pre>newSubscription()</code> function available
in the <code v-pre>HasSubscriptions</code> trait. First, retrieve an instance of your subscriber model, which typically will be your user
model and an instance of the plan your user is subscribing to. Once you have retrieved the model instance, you may use
the <code v-pre>newSubscription</code> method to create the model's subscription.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span> <span class="token operator">=</span> <span class="token class-name static-context">User</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">newSubscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">,</span> <span class="token variable">$plan</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Main subscription'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The first argument passed to <code v-pre>newSubscription</code> method should be the identifier tag of the subscription. If your
application offer a single subscription, you might call this <code v-pre>main</code> or <code v-pre>primary</code>. The second argument is the plan
instance your user is subscribing to and the third argument is a human readable name for your subscription.</p>
<h2 id="change-its-plan" tabindex="-1"><a class="header-anchor" href="#change-its-plan"><span>Change its Plan<a name="change-plan"></a></span></a></h2>
<p>You can change subscription plan easily as follows:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$subscription</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Change subscription plan</span>
<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token function">changePlan</span><span class="token punctuation">(</span><span class="token variable">$plan</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If both plans (current and new plan) have the same billing frequency (e.g., <code v-pre>invoice_period</code> and <code v-pre>invoice_interval</code>) the
subscription will retain the same billing dates. If the plans don't have the same billing frequency, the subscription
will have the new plan billing frequency, starting on the day of the change.</p>
<p><em>Subscription usage data will be cleared</em> by default, unless <code v-pre>false</code> is given as second parameter.</p>
<p>Also, if the new plan has a trial period, and it's a new subscription, the trial period will be applied.</p>
<h2 id="subscriber-s-subscriptions" tabindex="-1"><a class="header-anchor" href="#subscriber-s-subscriptions"><span>Subscriber's subscriptions</span></a></h2>
<p>Retrieve subscriptions of subscriber.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Get user subscriptions</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token property">subscriptions</span><span class="token punctuation">;</span>

<span class="token comment">// Get user active subscriptions</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token property">activeSubscriptions</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="subscription-feature-usage" tabindex="-1"><a class="header-anchor" href="#subscription-feature-usage"><span>Subscription Feature Usage<a name="subscription-feature-usage"></a></span></a></h2>
<p>There are multiple ways to determine the usage and ability of a particular feature in the subscriber's subscription, the
most common one is <code v-pre>canUseFeature</code>:</p>
<p>The <code v-pre>canUseFeature</code> method returns <code v-pre>true</code> or <code v-pre>false</code> depending on multiple factors:</p>
<ul>
<li>Subscription has not ended.</li>
<li>Feature <em>is enabled</em>.</li>
<li>Feature value isn't <code v-pre>0</code>/<code v-pre>false</code>/<code v-pre>NULL</code>.</li>
<li>Or feature has remaining uses available.</li>
</ul>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">canUseFeature</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Other feature methods on the user subscription instance are:</p>
<ul>
<li><code v-pre>getFeatureUsage</code>: returns how many times the user has used a particular feature.</li>
<li><code v-pre>getFeatureRemainings</code>: returns available uses for a particular feature.</li>
<li><code v-pre>getFeatureValue</code>: returns the feature value.</li>
</ul>
<blockquote>
<p>All methods share the same signature: e.g. <code v-pre>$user-&gt;subscription('main')-&gt;getFeatureUsage('social_profiles');</code>.</p>
</blockquote>
<h3 id="record-feature-usage" tabindex="-1"><a class="header-anchor" href="#record-feature-usage"><span>Record Feature Usage<a name="record-feature-usage"></a></span></a></h3>
<p>In order to effectively use the ability methods you will need to keep track of every usage of each feature (or at least
those that require it). You may use the <code v-pre>recordFeatureUsage</code> method available through the user <code v-pre>subscription()</code> method:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">recordFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The <code v-pre>recordFeatureUsage</code> method accepts 3 parameters: the first one is the feature's tag, the second one is the quantity
of uses to add (default is <code v-pre>1</code>), and the third one indicates if the addition should be incremental (default behavior),
when disabled the usage will be override by the quantity provided. E.g.:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Increment by 1</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">recordFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Override with 3</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">recordFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token constant boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="reduce-feature-usage" tabindex="-1"><a class="header-anchor" href="#reduce-feature-usage"><span>Reduce Feature Usage<a name="reduce-feature-usage"></a></span></a></h3>
<p>Reducing the feature usage is <em>almost</em> the same as incrementing it. Here we only <em>substract</em> a given quantity (default
is <code v-pre>1</code>) to the actual usage:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">reduceFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="clear-the-subscription-usage-data" tabindex="-1"><a class="header-anchor" href="#clear-the-subscription-usage-data"><span>Clear the Subscription Usage data<a name="clear-subscription-usage-data"></a></span></a></h3>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">usage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">delete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="check-subscription-status" tabindex="-1"><a class="header-anchor" href="#check-subscription-status"><span>Check Subscription status<a name="check-subscription-status"></a></span></a></h2>
<p>For a subscription to be considered active <em>one of the following must be <code v-pre>true</code></em>:</p>
<ul>
<li>Subscription has an active trial.</li>
<li>Subscription <code v-pre>ends_at</code> is in the future.</li>
</ul>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">isSubscribedTo</span><span class="token punctuation">(</span><span class="token variable">$planId</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Alternatively you can use the following methods available in the subscription model:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isActive</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isCanceled</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">hasEnded</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isOnTrial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>Canceled subscriptions with an active trial or <code v-pre>ends_at</code> in the future are considered active.</p>
</blockquote>
<h2 id="renew-a-subscription" tabindex="-1"><a class="header-anchor" href="#renew-a-subscription"><span>Renew a Subscription<a name="renew-subscription"></a></span></a></h2>
<p>To renew a subscription you may use the <code v-pre>renew</code> method available in the subscription model. This will set a
new <code v-pre>ends_at</code> date based on the selected plan and <em>will clear the usage data</em> of the subscription.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">renew</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><em>Canceled subscriptions with an ended period can't be renewed.</em></p>
<h2 id="cancel-a-subscription" tabindex="-1"><a class="header-anchor" href="#cancel-a-subscription"><span>Cancel a Subscription<a name="cancel-subscription"></a></span></a></h2>
<p>To cancel a subscription, simply use the <code v-pre>cancel</code> method on the user's subscription:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>By default the subscription will remain active until the end of the period, you may pass <code v-pre>true</code> to end the
subscription <em>immediately</em>:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token constant boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="scopes" tabindex="-1"><a class="header-anchor" href="#scopes"><span>Scopes<a name="scopes"></a></span></a></h2>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Get subscriptions by plan</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">byPlanId</span><span class="token punctuation">(</span><span class="token variable">$planId</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get bookings of the given user</span>
<span class="token variable">$user</span> <span class="token operator">=</span> <span class="token class-name class-name-fully-qualified static-context"><span class="token punctuation">\</span>App<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>User</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$bookingsOfUser</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">ofSubscriber</span><span class="token punctuation">(</span><span class="token variable">$user</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 

<span class="token comment">// Get subscriptions with trial ending in 3 days</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndingTrial</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with ended trial</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndedTrial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with period ending in 3 days</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndingPeriod</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with ended period</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndedPeriod</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


