<template><div><h1 id="plan-subscription-model" tabindex="-1"><a class="header-anchor" href="#plan-subscription-model"><span>Plan Subscription Model</span></a></h1>
<h2 id="create-a-subscription" tabindex="-1"><a class="header-anchor" href="#create-a-subscription"><span>Create a Subscription</span></a></h2>
<p>You can subscribe a user (or any model correctly traited) to a plan by using the <code v-pre>newSubscription()</code> function available
in the <code v-pre>HasSubscriptions</code> trait. First, retrieve an instance of your subscriber's model, which typically will be your
user model and an instance of the plan your subscriber is subscribing to. Once you have retrieved the model instance,
you may use the <code v-pre>newSubscription</code> method to create the model's subscription.</p>
<p>The subscription is made as a <em>snapshot</em> using current plan details as a template. Same happens with subscription
features. When you create a subscription a copy of the Plan Features is made into your Plan Subscription Features.</p>
<p>If related plan is modified in the future, subscriber's subscription stays as it was, price, invoicing and features
are &quot;frozen&quot; unless
<RouteLink to="/v5.x/models/plan-subscription-model.html#revert-overridden-plan-subscription-features">manually synchronized</RouteLink> with related plan.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span> <span class="token operator">=</span> <span class="token class-name static-context">User</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">newSubscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">,</span> <span class="token variable">$plan</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Main subscription'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Customer main subscription'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>First argument passed to <code v-pre>newSubscription</code> method should be the identifier tag of the subscription. If your
application offers a single subscription, you might call this <code v-pre>main</code> or <code v-pre>primary</code>.</li>
<li>Second argument is the plan instance your subscriber is subscribing to.</li>
<li>Third argument is a human-readable name for your subscription.</li>
<li>Fourth argument is a description.</li>
<li>Fifth argument is a start date for the subscription.</li>
</ul>
<h2 id="change-its-plan" tabindex="-1"><a class="header-anchor" href="#change-its-plan"><span>Change its Plan</span></a></h2>
<p>You can change subscription related plan easily as follows:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$subscription</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Change subscription plan clearing usage and synchronizing invoicing periods</span>
<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token function">changePlan</span><span class="token punctuation">(</span><span class="token variable">$plan</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Change subscription plan and keep usage</span>
<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token function">changePlan</span><span class="token punctuation">(</span><span class="token variable">$plan</span><span class="token punctuation">,</span> <span class="token constant boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Change subscription plan, keep usage and invoicing data</span>
<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token function">changePlan</span><span class="token punctuation">(</span><span class="token variable">$plan</span><span class="token punctuation">,</span> <span class="token constant boolean">false</span><span class="token punctuation">,</span> <span class="token constant boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Subscription usage data will be cleared by default, unless <code v-pre>false</code> is given as second parameter.</p>
<p>If you want the same billing frequency (<code v-pre>invoice_period</code> and <code v-pre>invoice_interval</code>) set third parameter to <code v-pre>true</code>
and subscription will inherit plan's billing frequency. If you want to keep current subscription invoice intervals, set
to <code v-pre>false</code>. By default, invoice details are synchronized with new plan.</p>
<ul>
<li>Plan change will adjust existing features to the ones in the new plan.</li>
<li>Change will also remove features attached to old plan.</li>
<li>Existent features that where previously attached without plan but exist in the new plan now will use plan values.</li>
<li>Features not attached to a plan and nonexistent in new plan will remain the same.</li>
</ul>
<h2 id="change-pricing-and-other-details" tabindex="-1"><a class="header-anchor" href="#change-pricing-and-other-details"><span>Change pricing and other details</span></a></h2>
<p>You can change the price or details without affecting attached features or plan. With this feature you can set prices
individually for every subscriber.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$subscription</span> <span class="token operator">=</span> <span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token property">description</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'Main description with great discount'</span><span class="token punctuation">;</span>
<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token property">price</span> <span class="token operator">=</span> <span class="token number">12</span><span class="token punctuation">;</span>

<span class="token variable">$subscription</span><span class="token operator">-></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="revert-custom-subscription-changes-resynchronize-to-plan" tabindex="-1"><a class="header-anchor" href="#revert-custom-subscription-changes-resynchronize-to-plan"><span>Revert custom subscription changes (resynchronize to plan)</span></a></h3>
<p>You can revert changes made to subscription with function <code v-pre>syncPlan</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Synchronize price, invoicing and tier with related plan</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">syncPlan</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Synchronize plan and also features</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">syncPlan</span><span class="token punctuation">(</span><span class="token constant">null</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>syncPlan()</code> accepts 3 parameters. First parameter is a <code v-pre>Plan</code>, if you want to synchronize with current plan
(default behaviour), set to <code v-pre>null</code>. Second is <code v-pre>bool</code> for synchronizing also invoicing details (period and interval),
default behaviour is to synchronize <code v-pre>true</code>. The third one is <code v-pre>bool</code> to also synchronize features.</p>
<h2 id="grace" tabindex="-1"><a class="header-anchor" href="#grace"><span>Grace <Badge text="new in v5.0" type="tip"/></span></a></h2>
<p>Grace period is the extra time the subscription will be considered active after it has ended.</p>
<h3 id="grace-related-functions" tabindex="-1"><a class="header-anchor" href="#grace-related-functions"><span>Grace related functions</span></a></h3>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">hasGrace</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns boolean indicating if subscription has grace period</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getGraceTotalDurationIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns duration integer in set Carbon interval (second, day, month...)</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getGraceStartDate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns grace start date (a.k.a. subscription end date)</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getGraceEndDate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns grace end date</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getGraceTotalDurationIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days grace lasts</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getGracePeriodUsageIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days of grace consumed</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getGracePeriodRemainingUsageIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days until subscription grace ends</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">hasStartedGrace</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns boolean indicating if grace period is over</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">hasEndedGrace</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns boolean indicating if grace period is over</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="subscriber-s-subscriptions" tabindex="-1"><a class="header-anchor" href="#subscriber-s-subscriptions"><span>Subscriber's subscriptions</span></a></h2>
<p>Retrieve subscriptions of subscriber.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Get user subscriptions</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token property">subscriptions</span><span class="token punctuation">;</span>

<span class="token comment">// Get user active subscriptions</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token property">activeSubscriptions</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="subscriber-s-main-or-only-subscription" tabindex="-1"><a class="header-anchor" href="#subscriber-s-main-or-only-subscription"><span>Subscriber's main or only subscription</span></a></h2>
<p>Since usually projects work with only one subscription or one primary, you have to set the tag for it in the
config <code v-pre>main_subscription_tag</code>.</p>
<p>If your user only has one subscription, <code v-pre>subscription()</code> will return the only one the subscriber has. If has more, it
will fall to default. Default is <code v-pre>main</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// config/subby.php</span>
<span class="token keyword">return</span> <span class="token punctuation">[</span>
    <span class="token string single-quoted-string">'main_subscription_tag'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'main'</span><span class="token punctuation">,</span>
    <span class="token operator">...</span>
<span class="token punctuation">]</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Then:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// This retrieves user's only one subscription or 'main' from config:</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="subscription-feature-usage" tabindex="-1"><a class="header-anchor" href="#subscription-feature-usage"><span>Subscription Feature Usage</span></a></h2>
<p>You can determine the usage and ability of a particular feature in the subscriber's subscription with <code v-pre>canUseFeature</code>:</p>
<p>The <code v-pre>canUseFeature</code> method returns <code v-pre>true</code> or <code v-pre>false</code> depending on multiple factors:</p>
<ul>
<li>Subscription is active (on trial or currently in period).</li>
<li>Feature <em>is enabled</em> (<code v-pre>true</code>).</li>
<li>Feature value isn't <code v-pre>0</code>/<code v-pre>false</code>/<code v-pre>NULL</code>.</li>
<li>Feature has remaining uses available.</li>
</ul>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">canUseFeature</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Other feature methods on the user subscription instance are:</p>
<ul>
<li><code v-pre>getFeatureUsage</code>: returns how many times the user has used a particular feature.</li>
<li><code v-pre>getFeatureRemainings</code>: returns available uses for a particular feature.</li>
<li><code v-pre>getFeatureValue</code>: returns the feature value.</li>
</ul>
<p>All methods share the same signature: e.g. <code v-pre>$user-&gt;subscription('main')-&gt;getFeatureUsage('social_profiles');</code>.</p>
<h3 id="record-feature-usage" tabindex="-1"><a class="header-anchor" href="#record-feature-usage"><span>Record Feature Usage <Badge text="updated in v5.0" type="warning"/></span></a></h3>
<div class="custom-container tip"><p class="custom-container-title">New in 5.0</p>
<p>Check if subscriber can use feature before recording use</p>
</div>
<p>In order to effectively use the ability methods you will need to keep track of every usage of each feature (or at least
those that require it). You may use the <code v-pre>recordFeatureUsage</code> method available through the user <code v-pre>subscription()</code> method:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">recordFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>When recording feature <code v-pre>canUseFeature</code> is already called within the function, so you do not have to check every time.
<code v-pre>UsageDenied</code> Exception is thrown if subscriber cannot use the feature.</p>
<p>The <code v-pre>recordFeatureUsage</code> method accepts 3 parameters: the first one is the feature's tag, the second one is the quantity
of uses to add (default is <code v-pre>1</code>), and the third one indicates if the addition should be incremental (default behavior),
when disabled the usage will be overridden by the quantity provided.</p>
<details class="custom-container details"><summary>Click me to view example code</summary>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Increment by 1</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">recordFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Override with 3</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">recordFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token constant boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></details>
<h3 id="reduce-feature-usage" tabindex="-1"><a class="header-anchor" href="#reduce-feature-usage"><span>Reduce Feature Usage</span></a></h3>
<p>Reducing the feature usage is <em>almost</em> the same as incrementing it. Here we only <em>substract</em> a given quantity (default
is <code v-pre>1</code>) to the actual usage:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">reduceFeatureUsage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="clear-the-subscription-usage-data" tabindex="-1"><a class="header-anchor" href="#clear-the-subscription-usage-data"><span>Clear the Subscription Usage data</span></a></h3>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">usage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">delete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="check-subscription-status" tabindex="-1"><a class="header-anchor" href="#check-subscription-status"><span>Check Subscription status</span></a></h2>
<p>For a subscription to be considered active one of the following must be <code v-pre>true</code>:</p>
<ul>
<li>Subscription has an active trial.</li>
<li>Subscription <code v-pre>ends_at</code> is in the future.</li>
</ul>
<p>Alternatively you can use the following methods available in the subscription model:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isActive</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isCanceled</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">hasEnded</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">hasEndedTrial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isOnTrial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// To know if subscription has the same values as related plan or has been changed</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isAltered</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="remaining-price-prorate" tabindex="-1"><a class="header-anchor" href="#remaining-price-prorate"><span>Remaining price prorate <Badge text="updated in v5.0" type="warning"/></span></a></h3>
<div class="custom-container danger"><p class="custom-container-title">Breaking change in v5.0</p>
<p>Renamed <code v-pre>getRemainingPriceProrate</code> to  <code v-pre>getSubscriptionRemainingUsagePriceProrate</code></p>
</div>
<p>You can get what is the remaining prorated amount until subscription invoice period ends.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getSubscriptionRemainingUsagePriceProrate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Ex: 10 day subscription of price 10.00, on day 6, returns 4</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="trial-period-time-related-functions" tabindex="-1"><a class="header-anchor" href="#trial-period-time-related-functions"><span>Trial period time related functions <Badge text="updated in v5.0" type="warning"/></span></a></h3>
<div class="custom-container danger"><p class="custom-container-title">Breaking change in v5.0</p>
<p>Renamed <code v-pre>getDaysUntilTrialEnds</code> to <code v-pre>getTrialPeriodRemainingUsageIn</code></p>
</div>
<p>You can get some information about duration in your trial with:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getTrialStartDate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// When did the trial start</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getTrialTotalDurationIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days trial lasts</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getTrialPeriodUsageIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days of trial consumed</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getTrialPeriodRemainingUsageIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days until subscription trial ends</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You can use Carbon accepted intervals (in singular): <code v-pre>year</code>,<code v-pre>month</code>,<code v-pre>day</code>,<code v-pre>hour</code>,<code v-pre>minute</code>,<code v-pre>second</code>,<code v-pre>microsecond</code>...</p>
<h3 id="subscription-period-time-related-functions" tabindex="-1"><a class="header-anchor" href="#subscription-period-time-related-functions"><span>Subscription period time related functions <Badge text="updated in v5.0" type="warning"/></span></a></h3>
<div class="custom-container danger"><p class="custom-container-title">Breaking change in v5.0</p>
<p>Renamed <code v-pre>getTotalDurationInDays</code> to <code v-pre>getSubscriptionTotalDurationIn</code>
<code v-pre>getDaysUntilEnds</code> to <code v-pre>getSubscriptionPeriodRemainingUsageIn</code></p>
</div>
<p>You can get some information about duration in your subscription with:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getSubscriptionTotalDurationIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days subscription lasts</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getSubscriptionPeriodUsageIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days of subscription consumed</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getSubscriptionPeriodRemainingUsageIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'day'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Returns number of days until subscription ends</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You can use Carbon accepted intervals (in singular): <code v-pre>year</code>,<code v-pre>month</code>,<code v-pre>day</code>,<code v-pre>hour</code>,<code v-pre>minute</code>,<code v-pre>second</code>,<code v-pre>microsecond</code>...</p>
<h2 id="revert-overridden-plan-subscription-features" tabindex="-1"><a class="header-anchor" href="#revert-overridden-plan-subscription-features"><span>Revert overridden plan subscription features</span></a></h2>
<p>You can revert all feature changes made to subscription that are related to a plan.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Resynchronize features</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">syncPlanFeatures</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Now all plan features available in subscription's related plan will be reset in subscription feature. If your subscriber
has attached manually a feature that was not previously available in plan, but now is, your custom subscription feature
will be related to plan feature and will be overridden with plan's feature details in this synchronization.</p>
<h3 id="other" tabindex="-1"><a class="header-anchor" href="#other"><span>Other</span></a></h3>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Check if subscription is free</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">isFree</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Check subscriber to plan</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">isSubscribedTo</span><span class="token punctuation">(</span><span class="token variable">$planId</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Canceled subscriptions with an active trial or <code v-pre>ends_at</code> in the future are considered active.</p>
<h2 id="renew-a-subscription" tabindex="-1"><a class="header-anchor" href="#renew-a-subscription"><span>Renew a Subscription <Badge text="updated in v5.0" type="tip"/></span></a></h2>
<div class="custom-container tip"><p class="custom-container-title">New in 5.0</p>
<p>Now you can multiply the times the period is renewed</p>
</div>
<p>To renew a subscription you may use the <code v-pre>renew</code> method available in the subscription model. This will set a
new <code v-pre>ends_at</code> date based on the selected plan.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">renew</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">renew</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// This will triple the periods. CAUTION: If your subscription is 2 'month', you'll get 6 'month'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Canceled subscriptions can't be renewed. Renewing a subscription with trial period ends it.</p>
<p>When a subscription has already ended time ago and now is renewed, period will be set as if subscription started today, but when
a subscription is still ongoing and renewed, start date is kept and end date is extended by the amount of periods specified.</p>
<h2 id="cancel-a-subscription" tabindex="-1"><a class="header-anchor" href="#cancel-a-subscription"><span>Cancel a Subscription</span></a></h2>
<p>To cancel a subscription, simply use the <code v-pre>cancel</code> method on the user's subscription:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="immediately" tabindex="-1"><a class="header-anchor" href="#immediately"><span>Immediately</span></a></h3>
<p>By default the subscription will remain active until the end of the period, you may pass <code v-pre>true</code> to end the
subscription <em>immediately</em>:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token constant boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="fallback-plan" tabindex="-1"><a class="header-anchor" href="#fallback-plan"><span>Fallback plan</span></a></h3>
<div class="custom-container tip"><p class="custom-container-title">New in 5.0</p>
<p>Now you can specify in config a fallback plan</p>
</div>
<p>If a <code v-pre>fallback_plan_tag</code> is not <code v-pre>null</code> in config, when <code v-pre>cancel</code> is called, subscription will not be canceled but changed
to fallback plan.</p>
<p>To cancel subscription and ignore fallback, a second parameter is available on <code v-pre>cancel</code> method:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token constant boolean">false</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="uncancel-a-subscription" tabindex="-1"><a class="header-anchor" href="#uncancel-a-subscription"><span>Uncancel a subscription</span></a></h2>
<p>To uncancel a subscription, simply use the <code v-pre>uncancel</code> method on the user's subscription:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">uncancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="scopes" tabindex="-1"><a class="header-anchor" href="#scopes"><span>Scopes</span></a></h2>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Get subscriptions by plan</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">byPlanId</span><span class="token punctuation">(</span><span class="token variable">$planId</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get bookings of the given user</span>
<span class="token variable">$user</span> <span class="token operator">=</span> <span class="token class-name class-name-fully-qualified static-context"><span class="token punctuation">\</span>App<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>User</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$bookingsOfUser</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">ofSubscriber</span><span class="token punctuation">(</span><span class="token variable">$user</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 

<span class="token comment">// Get subscriptions with trial ending in 3 days</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndingTrial</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with ended trial</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndedTrial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with period ending in 3 days</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndingPeriod</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with ended period</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">findEndedPeriod</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get subscriptions with period ending in 3 days filtered by the subscription tag</span>
<span class="token variable">$subscriptions</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">getByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'company'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">findEndingPeriod</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


