<template><div><h1 id="plan-subscription-feature-model" tabindex="-1"><a class="header-anchor" href="#plan-subscription-feature-model"><span>Plan Subscription Feature Model</span></a></h1>
<p>This model relates to which features has a Subscription.</p>
<h2 id="how-does-it-work" tabindex="-1"><a class="header-anchor" href="#how-does-it-work"><span>How does it work?</span></a></h2>
<p>A <RouteLink to="/v4.x/models/plan-subscription-model.html">subscription</RouteLink> has features that can be used. Subscription Features are related but
independent from Plan Features. When a subscription is created or a feature is attached, it makes a copy so it's
decoupled and changes to related plan will not be applied automatically.</p>
<h2 id="how-do-subscription-features-relate-to-plan-features" tabindex="-1"><a class="header-anchor" href="#how-do-subscription-features-relate-to-plan-features"><span>How do Subscription Features relate to Plan Features?</span></a></h2>
<p>Plan Subscription Feature has two relationships to Plan, if you force it they can be two different plans, usually both
will only lead to one Plan.</p>
<h3 id="via-subscription" tabindex="-1"><a class="header-anchor" href="#via-subscription"><span>Via Subscription</span></a></h3>
<p><code v-pre>PlanSubscriptionFeature</code> belongs <strong>always</strong> to one <code v-pre>PlanSubscription</code>, and it belongs <strong>always</strong> to one <code v-pre>Plan</code>.</p>
<h3 id="via-plan-feature" tabindex="-1"><a class="header-anchor" href="#via-plan-feature"><span>Via Plan Feature</span></a></h3>
<p><code v-pre>PlanSubscriptionFeature</code> <strong>may</strong> belong to one <code v-pre>PlanFeature</code>, and it belongs <strong>always</strong> to one <code v-pre>Plan</code>.</p>
<h2 id="add-features-to-a-subscription" tabindex="-1"><a class="header-anchor" href="#add-features-to-a-subscription"><span>Add features to a subscription</span></a></h2>
<h3 id="inherited-from-plan-when-subscribed" tabindex="-1"><a class="header-anchor" href="#inherited-from-plan-when-subscribed"><span>Inherited from plan when subscribed</span></a></h3>
<p>Features are assigned and inherited from plan when user is subscribed to a plan. This makes a copy of current plan
features into the subscription.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">newSubscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">,</span> <span class="token variable">$plan</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Main subscription'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Customer main subscription'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Now subscriber's subscription will have all current plan features.</p>
<h3 id="manually-assign-without-relation-to-a-plan-feature" tabindex="-1"><a class="header-anchor" href="#manually-assign-without-relation-to-a-plan-feature"><span>Manually assign without relation to a plan feature</span></a></h3>
<p>A plan has <code v-pre>social_profiles</code> feature. When subscriber is subscribed to that plan, the subscription can now
use <code v-pre>social_profiles</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// You can also attach directly features to user</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">features</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
    <span class="token string single-quoted-string">'tag'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'pictures_per_social_profile'</span><span class="token punctuation">,</span> 
    <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'Pictures per social profile'</span><span class="token punctuation">,</span> 
    <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token number">30</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'sort_order'</span> <span class="token operator">=></span> <span class="token number">10</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'resettable_period'</span> <span class="token operator">=></span> <span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string single-quoted-string">'resettable_interval'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'month'</span>
<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Now user can also make use of the <code v-pre>pictures_per_social_profile</code> feature, and it will be reset monthly.</p>
<h3 id="override-existing-feature-values" tabindex="-1"><a class="header-anchor" href="#override-existing-feature-values"><span>Override existing feature values</span></a></h3>
<p>If subscriber has inherited a feature from a plan, there cannot be two features with the same tag attached to
subscriber. But since subscription features do not depend anymore on plan features, you can override said feature.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Modify feature limit for subscriber</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getFeatureByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'pictures_per_social_profile'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">[</span>     
       <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token number">60</span><span class="token punctuation">,</span>
    <span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Just like that, our user will be always capable of using 60 pictures, no matter what the plan feature limit is.</p>
<h2 id="revert-all-changes-and-sync-to-plan" tabindex="-1"><a class="header-anchor" href="#revert-all-changes-and-sync-to-plan"><span>Revert all changes and sync to plan</span></a></h2>
<p>You can revert all your changes to a subscription an return to a clean copy of current subscription's Plan Features.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Resync features with subscription's current plan</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">syncPlanFeatures</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>syncPlanFeatures</code> accepts one parameter <code v-pre>Plan</code>, in case you want a clean copy of another plan that is not current plan.</p>
<h2 id="revert-one-change" tabindex="-1"><a class="header-anchor" href="#revert-one-change"><span>Revert one change</span></a></h2>
<p>You can revert one feature to a subscription and return to a clean copy of current subscription's Plan Feature or
current
<code v-pre>Plan Feature</code> in case it's not the same.</p>
<h4 id="revert-to-subscription-s-plan-value" tabindex="-1"><a class="header-anchor" href="#revert-to-subscription-s-plan-value"><span>Revert to Subscription's Plan value</span></a></h4>
<p>It will sync your subscription's feature retrieving your Plan Feature via Plan in Subscription related
in <code v-pre>subscription_id</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Resync feature with subscription's current plan</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getFeatureByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'pictures_per_social_profile'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">syncPlanSubscription</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="revert-to-subscription-s-feature-plan-feature-value" tabindex="-1"><a class="header-anchor" href="#revert-to-subscription-s-feature-plan-feature-value"><span>Revert to Subscription's Feature Plan Feature value</span></a></h4>
<p>It will sync your subscription's feature retrieving your Plan Feature via Plan Feature in <code v-pre>plan_feature_id</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Resync feature with subscription's current plan</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getFeatureByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'pictures_per_social_profile'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">syncPlanFeature</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="retrieve-features-without-plan" tabindex="-1"><a class="header-anchor" href="#retrieve-features-without-plan"><span>Retrieve features without plan</span></a></h2>
<p>If you manually attached features that were not included in related subscription plan, you can retrieve them via scope.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">// Retrieve features that are not tied in any form to a plan</span>
<span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">features</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">withoutPlan</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="feature-usage" tabindex="-1"><a class="header-anchor" href="#feature-usage"><span>Feature usage</span></a></h2>
<p>See also <RouteLink to="/v4.x/models/models/plan-subscription-model.html#subscription-feature-usage">subscription feature usage</RouteLink>.</p>
<p>Plan subscription feature usage object can be retrieved via <code v-pre>usage()</code> relationship:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getFeatureByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token property">usage</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>To get all the subscription features along with their usage:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token variable">$user</span><span class="token operator">-></span><span class="token function">subscription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'main'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">features</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">with</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'usage'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></div></template>


