<template><div><h1 id="plan-feature-model" tabindex="-1"><a class="header-anchor" href="#plan-feature-model"><span>Plan Feature Model</span></a></h1>
<p>This model relates to which features has a Plan. This features will be attached to every new subscription.</p>
<h2 id="create-plan-features" tabindex="-1"><a class="header-anchor" href="#create-plan-features"><span>Create plan features</span></a></h2>
<p>Features are things that your plan allows subscribers to do. The obligatory fields are: <code v-pre>tag</code>, <code v-pre>name</code>, and <code v-pre>value</code>. The
value of the feature tells if or how many times the subscriber is allowed to use it. When setting a feature that should
be active or not, use written strings 'true' or 'false', otherwise use an integer to tell how many times it can be used.
If in the higher plan you want to give unlimited access to the &quot;counted&quot; feature, use 'true' as well. If you want the
usage of features to be reset on a regular basis, provide optional <code v-pre>resettable_period</code> and <code v-pre>resettable_interval</code> fields.</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>Plan</span><span class="token punctuation">;</span>

<span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Create multiple plan features at once</span>
<span class="token variable">$plan</span><span class="token operator">-></span><span class="token function">features</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">saveMany</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
    <span class="token keyword">new</span> <span class="token class-name">PlanFeature</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'tag'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'social_profiles'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'Social profiles available'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'sort_order'</span> <span class="token operator">=></span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">new</span> <span class="token class-name">PlanFeature</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'tag'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'posts_per_social_profile'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'Scheduled posts per profile'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'sort_order'</span> <span class="token operator">=></span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'resettable_period'</span> <span class="token operator">=></span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'resettable_interval'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'month'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">new</span> <span class="token class-name">PlanFeature</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'tag'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'analytics'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'Analytics'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token constant boolean">true</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'sort_order'</span> <span class="token operator">=></span> <span class="token number">15</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="get-plan-feature-value" tabindex="-1"><a class="header-anchor" href="#get-plan-feature-value"><span>Get Plan Feature value</span></a></h2>
<p>Say you want to show the value of the feature <em>posts_per_social_profile</em> from above. You can do so in many ways:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>Plan</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>PlanFeature</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>PlanSubscription</span><span class="token punctuation">;</span>

<span class="token variable">$plan</span> <span class="token operator">=</span> <span class="token class-name static-context">Plan</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Use the plan instance to get feature's value</span>
<span class="token variable">$amountOfPosts</span> <span class="token operator">=</span> <span class="token variable">$plan</span><span class="token operator">-></span><span class="token function">getFeatureByTag</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'posts_per_social_profile'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token property">value</span><span class="token punctuation">;</span>

<span class="token comment">// Query the feature itself directly</span>
<span class="token variable">$amountOfPosts</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanFeature</span><span class="token operator">::</span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'tag'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'posts_per_social_profile'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">first</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token property">value</span><span class="token punctuation">;</span>

<span class="token comment">// Get feature value through the subscription instance</span>
<span class="token variable">$amountOfPosts</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanSubscription</span><span class="token operator">::</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getFeatureValue</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'posts_per_social_profile'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="feature-options" tabindex="-1"><a class="header-anchor" href="#feature-options"><span>Feature Options</span></a></h2>
<p>Plan features are great for fine-tuning subscriptions, you can top up certain feature for X times of usage, so users may
then use it only for that amount. Features also have the ability to be resettable and then it's usage could be expired
too. See the following examples:</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Flixtechs<span class="token punctuation">\</span>Subby<span class="token punctuation">\</span>Models<span class="token punctuation">\</span>PlanFeature</span><span class="token punctuation">;</span>

<span class="token comment">// Find plan feature</span>
<span class="token variable">$feature</span> <span class="token operator">=</span> <span class="token class-name static-context">PlanFeature</span><span class="token operator">::</span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'tag'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'posts_per_social_profile'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">first</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Get feature reset date</span>
<span class="token variable">$feature</span><span class="token operator">-></span><span class="token function">getResetDate</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name class-name-fully-qualified"><span class="token punctuation">\</span>Carbon<span class="token punctuation">\</span>Carbon</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


